//ref https://www.canva.cn/sizes/wechat-official-account/

export default [
    {
        key: 'wechat',
        title: '微信',
        avatar: 'assets/avatar/weixin.png',
        lists: [
            {
                title: '公众号封面',
                width: 900,
                height: 383,
                w: 2.35,
                h: 1,
            },
            {
                title: '公众号小图',
                width: 200,
                height: 200,
                w: 1,
                h: 1,
            },
            {
                title: '内容引导图',
                width: 900,
                height: 500,
                w: 9,
                h: 5,
            },
            {
                title: '二维码名片',
                width: 600,
                height: 600,
                w: 1,
                h: 1,
            },
            {
                title: '视频号横版封面',
                width: 1080,
                height: 608,
                w: 16,
                h: 9,
            },
            {
                title: '视频号竖版封面',
                width: 1080,
                height: 1260,
                w: 6,
                h: 7,
            },
        ],
    },
    {
        key: 'xiaohongshu',
        title: '小红书',
        avatar: 'assets/avatar/xhs.png',
        lists: [
            {
                title: '封面 （竖版）',
                width: 1242,
                height: 1660,
                w: 3,
                h: 4,
            },
            {
                title: '封面（横版）',
                width: 800,
                height: 600,
                w: 4,
                h: 3,
            },
            {
                title: '背景图',
                width: 1000,
                height: 800,
                w: 5,
                h: 4,
            },
            {
                title: '配图（竖版）',
                width: 900,
                height: 1200,
                w: 3,
                h: 4,
            },
            {
                title: '配图（方版）',
                width: 1080,
                height: 1080,
                w: 1,
                h: 1,
            },
            {
                title: '配图（横版）',
                width: 1200,
                height: 900,
                w: 4,
                h: 3,
            },
        ],
    },
    {
        key: 'weibo',
        title: '微博',
        avatar: 'assets/avatar/weibo.png',
        lists: [
            {
                title: '主页封面图',
                width: 980,
                height: 300,
                w: 49,
                h: 15,
            },
            {
                title: '内容区域',
                width: 980,
                height: 900,
                w: 49,
                h: 45,
            },
            {
                title: '长图',
                width: 800,
                height: 2000,
                w: 2,
                h: 5,
            },
            {
                title: '头条封图',
                width: 980,
                height: 560,
                w: 7,
                h: 4,
            },
            {
                title: '焦点图片',
                width: 540,
                height: 260,
                w: 27,
                h: 13,
            },
        ],
    },
    {
        key: 'others',
        title: '其它',
        avatar: 'assets/avatar/other.png',
        lists: [
            {
                width: 1920,
                height: 1080,
                w: 16,
                h: 9,
            },
            {
                width: 1920,
                height: 1280,
                w: 3,
                h: 2,
            },
            {
                width: 1920,
                height: 1440,
                w: 4,
                h: 3,
            },
            {
                width: 1920,
                height: 1536,
                w: 5,
                h: 4,
            },
            {
                width: 1920,
                height: 1920,
                w: 1,
                h: 1,
            },
            {
                width: 1080,
                height: 1350,
                w: 4,
                h: 5,
            },
            {
                width: 1080,
                height: 1440,
                w: 3,
                h: 4,
            },
            {
                width: 1080,
                height: 1620,
                w: 2,
                h: 3,
            },
            {
                width: 1080,
                height: 1920,
                w: 9,
                h: 16,
            },
        ],
    },
];
